require "support/test_helper"

module Booklet
  class MarkdownParserTest < Minitest::Test
    context "Page with headings" do
      setup do
        @page_path = Fixtures.file("pages/page_with_headings.md")
        @page = page_from_fixture("pages/page_with_headings.md")
      end

      context "PageNode#ast" do
        should "return the markdown AST generated by parsing the page contents" do
          assert_kind_of Commonmarker::Node, @page.ast
        end
      end
    end
  end
end
